name: Test application

on:
  pull_request:
    branches: [ qa ]
  repository_dispatch:
    types: [ daily-build ]
jobs:
  set_java:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.create-matrix.outputs.matrix }}
    steps: 
      - name: Add JDK 8 to Java matrix
        run: |
          export JDKS=8
          echo "JDKS=$JDKS" >> $GITHUB_ENV
      - name: Add JDK 11 to Java matrix
        if: ${{ github.event_name == 'repository_dispatch'}}
        run: |
          export JDKS=$JDKS,11
          echo "JDKS=$JDKS" >> $GITHUB_ENV
      - name: Create JDK matrix
        id: create-matrix
        run: echo "::set-output name=matrix::{ \"jdk\":[$JDKS] }"
  build:
    runs-on: ubuntu-latest
    needs: [set_java]
    strategy:
      matrix: ${{ fromJson(needs.set_java.outputs.matrix) }}
    env:
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    defaults:
      run:
        working-directory: finish
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.jdk }}
    - run: unset _JAVA_OPTIONS
    - name: Modify pom.xml
      if: ${{ github.event_name == 'repository_dispatch'}}
      run: |
           sed -i "\#<artifactId>liberty-maven-plugin</artifactId>#a<configuration><install><runtimeUrl>https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/nightly/${{github.event.client_payload.dev-date}}/${{github.event.client_payload.dev-build}}</runtimeUrl></install></configuration>" pom.xml
           cat pom.xml
    - name: Modify Dockerfile
      if: ${{ github.event_name == 'repository_dispatch'}}
      run: sed -i "s;FROM openliberty/open-liberty:kernel-java8-openj9-ubi;FROM $DOCKER_USERNAME/olguides:$BUILDLEVEL;g"
    - name: Docker log in
      if: ${{ github.event_name == 'repository_dispatch'}}
      run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin;
    - name: Run tests
      run: ../scripts/travisTest.sh
    - name: Post tests
      if: always()
      run: |
           logsPath=$(find . -name "console.log");
           cat $logsPath | grep Launching
    - name: Archive server logs if failed
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: server-logs
        path: finish/target/liberty/wlp/usr/servers/guideServer/logs/
